spring:
  main:
    allow-circular-references: true
  application:
    name: spring security 08
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:spring_security.db;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  sql:
    init:
      platform: h2
      schema-locations: classpath:sql/schema-new.sql, classpath:org/springframework/security/oauth2/client/oauth2-client-schema.sql
      data-locations: classpath:sql/data-new.sql
      encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: b7e75a5bf48cf7d37ab309638a1e5024
            client-secret: TA00g5YkhLX4hF2MtbpTqS9GwWQX87zU
            scope: profile_nickname, profile_image
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    database: h2
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8080
jwt:
  header: token
  issuer: programmers
  client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  expiry-seconds: 60